# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180419_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='user name'),
        ),
    ]
