# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
