# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
