# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180426_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='introduction',
        ),
    ]
