# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180417_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='article.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
