# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_userprofile_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
