# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180417_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 9, 59, 37, 516016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 9, 59, 37, 517951, tzinfo=utc)),
        ),
    ]
