# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(null=True, upload_to='article_images'),
        ),
    ]
