# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180421_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='chinese_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
